INSERT INTO usuario (nombre, correo, contrasena,telefono,fecha_nac,direccion,provincia) VALUES 
("Angelica Reyes", "angelica.reyes1@utp.ac.pa","12345","6111-2222","2001-01-01","Panama centro","Panama");

INSERT INTO provincia_alojamiento (provincia, imagen_paisaje) VALUES
("Panama","panama.jpg"),
("Los Santos","lossantos.jpg"),
("Herrera","herrera.jpg"),
("Chiriqui","chiriqui.jpg"),
("Veraguas","veraguas.jpg"),
("Chorrera","chorrera.jpg"),
("Colon","colon.jpg"),
("Bocas del toro","bocas.jpg"),
("Coclé","cocle.jpg"),
("Darien","darien.jpg");

INSERT INTO alojamiento(id_lugar,precio_original, precio_oferta,impuestos,nombre_hotel,ubicacion,imagen,kilometros, descripcion)
VALUES
	(1,"PAB 54.99","PAB 48.55","PAB 6 de impuestos y cargos","Hotel principe","Bellavista Panama","hotelprincipe.jpg","a 1,3 km del centro", "Hotel con Habitacion doble, 1 cama doble grande"),
	(1,"PAB 199.99",null,"PAB 20 de impuestos y cargos","Waldorf Astoria Panamá","Bellavista Panama","waldorf.jpg","a 0,6 km del centro","Habitacion doble, una cama doble grande"),
    (1,"PAB 65.99","PAB 45.55","PAB 5 de impuestos y cargos","Hospedium Princess Hotel Panamá","Bellavista Panama","hospedium.jpg","a 300 m del centro", "Hotel con Habitacion doble, 1 cama doble grande"),
	(1,"PAB 49.99","PAB 38.99","PAB 4 de impuestos y cargos","Cresta Inn","Bellavista Panama","cresta.jpg","a 1,1 km del centro","Habitacion individual estandar, cuenta con varios tipos de camas, desayuno incluido"),
	(2,"PAB 54.99",null,"PAB 5 de impuestos y cargos","Selina River Venao","Playa Venao","selina.jpg","","Habitacion con baño compartido, cama grande, cancelacion GRATIS"),
    (2,"PAB 70.99",null,"PAB 7 de impuestos y cargos","Hotel Presidente Las Tablas","Las Tablas","presidente.jpg","","Habitacion doble Deluxe, cuenta con 2 camas dobles, cancelacion GRATIS"),
    (2,"PAB 75.99",null,"PAB 7 de impuestos y cargos","Hotel Punta Franca","Jobal","puntafranca.jpg","","Habitacion doble - 2 camas, cuenta con desayuno incluido"),
    (2,"PAB 139.99","PAB 132.99","PAB 13 de impuestos y cargos","Villa Marina Lodge & Condos","Playa Venao","marina.jpg","","Habitacion estandar, cama extragrande"),
	(3,"PAB 85.99",null,"PAB 5 de impuestos y cargos","Hotel Faranda Guayacanes","Chitré","faranda.jpg","","Habitacion con baño compartido, cama grande, cancelacion GRATIS"),
    (3,"PAB 40.99",null,"PAB 7 de impuestos y cargos","Hotel Rex","Chitre","rex.jpg","","Habitacion doble, cuenta con 1 cama dobles, cancelacion GRATIS"),
    (3,"PAB 80.99",null,"PAB 7 de impuestos y cargos","Gran Hotel Azuero","Chitre","azuero.jpg","","Habitacion doble - 2 camas, cuenta con desayuno incluido"),
    (3,"PAB 62.99",null,"PAB 13 de impuestos y cargos","Hotel Kevin","Los Santos","kevin.jpg","","Habitacion estandar, cama extragrande"),
    (4,"PAB 77.99",null,"PAB 5 de impuestos y cargos","Hampton by Hilton David, Panamá","David","hampton.jpg","","Habitacion con baño compartido, cama grande, cancelacion GRATIS"),
    (4,"PAB 84.99",null,"PAB 7 de impuestos y cargos","Hotel Ladera","Boquete","ladera.jpg","","Habitacion doble Deluxe, cuenta con 2 camas dobles, cancelacion GRATIS"),
    (4,"PAB 89.99",null,"PAB 7 de impuestos y cargos","Hotel Casa Grande Bambito","Cerro Punta","bambito.jpg","","Habitacion doble - 2 camas, cuenta con desayuno incluido"),
    (4,"PAB 64.99","PAB 54.99","PAB 13 de impuestos y cargos","Panama Camping Park","Bajo Boquete","park.jpg","","Habitacion estandar, cama extragrande"),
    (5,"PAB 66.99",null,"PAB 5 de impuestos y cargos","Hotel Galeria","Santiago de veraguas","galeria.jpg","","Habitacion con baño compartido, cama grande, cancelacion GRATIS"),
    (5,"PAB 102.99",null,"PAB 7 de impuestos y cargos","Vista Coiba Villas","Santa Catalina","coiba.jpg","","Habitacion doble Deluxe, cuenta con 2 camas dobles, cancelacion GRATIS"),
    (5,"PAB 93.99",null,"PAB 7 de impuestos y cargos","Hotel Punta Duarte","Los Duarte","duarte.jpg","","Habitacion doble - 2 camas, cuenta con desayuno incluido"),
    (5,"PAB 125.99","PAB 112.99","PAB 13 de impuestos y cargos","Hotel Mykonos","Santiago de Veraguas","mykonos.jpg","","Habitacion estandar, cama extragrande"),
    (6,"PAB 35.99",null,"PAB 5 de impuestos y cargos","Hotel America","La Chorrera","america.jpg","","Habitacion con baño compartido, cama grande, cancelacion GRATIS"),
    (6,"PAB 123.99",null,"PAB 7 de impuestos y cargos","Coronado Breezes","La Chorrera","coronado.jpg","","Habitacion doble Deluxe, cuenta con 2 camas dobles, cancelacion GRATIS"),
    (7,"PAB 35.99","PAB 28.99","PAB 5 de impuestos y cargos","La Cubana Hotel & Residencial","Colon","cubana.jpg","","Habitacion con baño compartido, cama grande, Oferta de Finales de Año"),
    (7,"PAB 90.99",null,"PAB 7 de impuestos y cargos","Radisson Colon 2000","Colon","radisson.jpg","","Habitacion doble Deluxe, cuenta con 2 camas dobles, cancelacion GRATIS"),
    (7,"PAB 98.99",null,"PAB 7 de impuestos y cargos","Paradise Island Beach Hotel","Isla Grande","paradise.jpg","","Habitacion doble - 2 camas, cuenta con desayuno incluido"),
    (7,"PAB 103.99",null,"PAB 13 de impuestos y cargos","Hotel Cocotal","Isla Grande","cocotal.jpg","","Habitacion estandar, cama extragrande"),
    (8,"PAB 53.99",null,"PAB 5 de impuestos y cargos","Selina Red Frog","Bocas del Toro","selina2.jpg","","Habitacion con baño compartido, cama grande, cancelacion GRATIS"),
    (8,"PAB 79.99",null,"PAB 7 de impuestos y cargos","Palmar Beach Lodge","Bocas del Toro","lodge.jpg","","Habitacion doble Deluxe, cuenta con 2 camas dobles, cancelacion GRATIS"),
    (8,"PAB 99.99",null,"PAB 7 de impuestos y cargos","Gran Hotel Bahia","Bocas del Toro","bahia.jpg","","Habitacion doble - 2 camas, cuenta con desayuno incluido"),
    (8,"PAB 250.99",null,"PAB 13 de impuestos y cargos","Eclypse de Mar Acqua Lodge","Bastimentos","eclypse.jpg","","Habitacion estandar, cama extragrande"),
    (9,"PAB 84.99",null,"PAB 5 de impuestos y cargos","The Golden Frog Inn","El Valle de Anton","golden.jpg","","Habitacion con baño compartido, cama grande, cancelacion GRATIS"),
    (9,"PAB 171.99",null,"PAB 7 de impuestos y cargos","Bijao Beach Resort - All Inclusive","Playa Blanca","bijao.jpg","","Habitacion doble Deluxe, cuenta con 2 camas dobles, Todas las comidas incluidas"),
    (9,"PAB 361.99","PAB 217.99","PAB 7 de impuestos y cargos","Royal Decameron Panamá - All Inclusive","Playa Blanca","decameron.jpg","","Habitacion doble - 2 camas,  Todas las comidas incluidas"),
    (9,"PAB 309.99","PAB 170.99","PAB 13 de impuestos y cargos","Riu Playa Blanca - All Inclusive","Playa Blanca","riu.jpg","","Habitacion estandar, cama extragrande"),
    (10,"PAB 75.99",null,"PAB 5 de impuestos y cargos","Quality Inn Darien-North Brunswick","Darien","quality.jpg","a 3,8 km del centro","Habitacion con baño compartido, cama grande, cancelacion GRATIS");
    
INSERT INTO habitaciones(id_alojamiento,nombre_habitacion, cama, precio) VALUES
(1,"Habitacion doble con baño compartido","1 cama grande","PAB 53.99"),
(1,"Habitacion pequeña con baño compartido","1 cama doble","PAB 60.99"),
(2,"Habitacion doble","1 cama grande","PAB 46.99"),
(2,"Suite junior","1 cama doble extragrande","PAB 84.99"),
(3,"Habitacion individual estandar","1 cama doble grande","PAB 38.99"),
(3,"Habitacion individual estandar","1 cama doble extragrande","PAB 40.99"),
(4,"Habitacion individual","1 cama doble","PAB 40.99"),
(4,"Habitacion grande con baño compartido","1 cama doble extragrande","PAB 45.99"),
(5,"Habitacion con baño compartido - Cama grande","1 cama doble y Wifi gratis","PAB 54.99"),
(5,"Tipi Micro","1 cama doble y Wifi gratis","PAB 60.99"),
(6,"Habitacion Doble Deluxe","2 camas doble y Wifi gratis, aire acondicionado, baño privado, TV de pantalla plana","PAB 95.99"),
(6,"Habitacion Doble Deluxe con cama extragrande","1 cama doble extragrande y Wifi gratis","PAB 70.99"),
(7,"Habitacion Doble 2 camas","2 camas individuales, vistas al jardin, aire acondicionado y Wifi gratis","PAB 75.99"),
(7,"Habitacion Doble Deluxe	con vistas a la piscina - 1 o 2 camas","2 camas extragrandes, Balcon, Aire acondicionado, Baño en la habitacion, Terraza, Wifi gratis","PAB 129.99"),
(8,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 132.99"),
(8,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 141.99"),
(9,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 85.99"),
(9,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 120.99"),
(10,"Habitacion estandar - Cama extragrande","1 cama doble grande. Habitacion sencilla, 1 noche","PAB 40.99"),
(10,"Habitacion Doble Deluxe","1 cama doble grande. Habitacion sencilla 1 noche, Wifi Gratis, 2 noches","PAB 48.99"),
(11,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 80.99"),
(11,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 94.99"),
(12,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 62.99"),
(12,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 84.99"),
(13,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 77.99"),
(13,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 92.99"),
(14,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 84.99"),
(14,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 121.99"),
(15,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 89.99"),
(15,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 72.99"),
(16,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 54.99"),
(16,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 62.99"),
(17,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 66.99"),
(17,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 112.99"),
(18,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 102.99"),
(18,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 146.99"),
(19,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 93.99"),
(19,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 56.99"),
(20,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 112.99"),
(20,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 125.99"),
(21,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 35.99"),
(21,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 45.99"),
(22,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 123.99"),
(22,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 131.99"),
(23,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 28.99"),
(23,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 46.99"),
(24,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 90.99"),
(24,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 98.99"),
(25,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 98.99"),
(25,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 156.99"),
(26,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 103.99"),
(26,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 76.99"),
(27,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 53.99"),
(27,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 60.99"),
(28,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 79.99"),
(28,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 101.99"),
(29,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 99.99"),
(29,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 121.99"),
(30,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 250.99"),
(30,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 190.99"),
(31,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 84.99"),
(31,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 112.99"),
(32,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 171.99"),
(32,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 101.99"),
(33,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 217.99"),
(33,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 182.99"),
(34,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 170.99"),
(34,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 123.99"),
(35,"Habitacion estandar - Cama extragrande","1 cama doble grande, Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 75.99"),
(35,"Habitacion Doble Deluxe","2 camas dobles,Piscina con vistas, Aire acondicionado, Baño en la habitacion, Wifi gratis","PAB 89.99");

INSERT INTO disponibilidad_habitacion(id_habitaciones,adultos,ninos) VALUES
(1,1,2),
(2,2,0),
(3,2,2),
(4,2,0),
(5,2,1),
(6,2,0),
(7,1,0),
(8,2,0),
(9,2,0),
(10,2,0),
(11,2,2),
(12,2,0),
(13,2,1),
(14,4,2),
(15,2,2),
(16,3,3),
(17,2,3),
(18,2,0),
(19,2,0),
(20,2,2),
(21,2,1),
(22,2,1),
(23,2,0),
(24,2,0),
(25,2,0),
(26,2,0),
(27,2,2),
(28,2,1),
(29,2,0),
(30,2,0),
(31,2,0),
(32,2,0),
(33,2,0),
(34,2,0),
(35,2,0),
(36,2,0),
(37,2,0),
(38,2,0),
(39,2,0),
(40,2,0),
(41,2,0),
(42,2,0),
(43,2,0),
(44,2,0),
(45,2,0),
(46,2,0),
(47,2,0),
(48,2,0),
(49,2,0),
(50,2,0),
(51,2,0),
(52,2,0),
(53,2,0),
(54,2,0),
(55,2,0),
(56,2,0),
(57,2,0),
(58,2,0),
(59,2,0),
(60,2,0),
(61,2,0),
(62,2,0),
(63,4,2),
(64,2,0),
(65,4,4),
(66,3,2),
(67,4,2),
(68,2,3),
(69,2,0),
(70,2,0);